### ISSUE TITLE
Environment configuration 

### ISSUE THREAD

**Issue by LeonLespri** [seed-labs/seed-labs#123]
![image](https://github.com/seed-labs/seed-labs/assets/105361870/882c6054-a5fe-423a-ba57-4588867efa95)

😶‍🌫️When I execute the following command
# Run the script that generates the container The output is in the output folder in the current directory
python3 simple-peering.py
🙌An error occurs:
]Traceback (most recent call last):
  File "simple-peering.py", line 4, in <module>
    from seedemu.layers import Base, Routing, Ebgp
  File "/home/leoncoolgirl/桌面/seed-emulator/seedemu/__init__.py", line 2, in <module>
    from .layers import *
  File "/home/leoncoolgirl/桌面/seed-emulator/seedemu/layers/__init__.py", line 6, in <module>
    from .Dnssec import Dnssec
  File "/home/leoncoolgirl/桌面/seed-emulator/seedemu/layers/Dnssec.py", line 4, in <module>
    from seedemu.services import DomainNameServer, DomainNameService
  File "/home/leoncoolgirl/桌面/seed-emulator/seedemu/services/__init__.py", line 11, in <module>
    from .EthereumService import *
  File "/home/leoncoolgirl/桌面/seed-emulator/seedemu/services/EthereumService/__init__.py", line 8, in <module>
    from .EthUtil import Genesis, AccountStructure, SmartContract, EthAccount
  File "/home/leoncoolgirl/桌面/seed-emulator/seedemu/services/EthereumService/EthUtil.py", line 8, in <module>
    from web3 import Web3
ModuleNotFoundError: No module named 'web3'

**Comment by kevin-w-du** [comment]
You can install the web3 module yourself.
